<footer class="site-footer">




	<div class="container-fluid">
	<div class="row-fluid">
	<div class="span4 offset1">
		<div class="posts post8">
		<ul class="social">
	      <li>Email: <a href="mailto:peter.wilkins@mayden.co.uk"> Peter Wilkins</a></li>
		  <li>Subscribe: <a href="/feed.xml">via RSS</a></li>
		  <li>Github: <a href="https://github.com/peter.wilkins.mayden">peter.wilkins.mayden</a></li>
		  <li>Twitter: <a href="https://twitter.com/peterwilkins801">peterwilkins801</a></li>
		 </ul>
	</div>
</div>
    <div class="span4 offset1">
        <p><?= $site_description ?></p>
    </div>
	</div>
  </div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</footer>
