<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<!-- Bootstrap-->
      <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen">


      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

  <title><?= $site_title ?></title>
  <meta name="description" content="<?= $site_description ?>">


  <link rel="alternate" type="application/rss+xml" title="<?= $site_title ?>" href="/feed.xml" />
  <link href='https://fonts.googleapis.com/css?family=Cabin|Source+Code+Pro' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="css/main.css" type="text/css">
  <link rel="stylesheet" href="styles/default.css">
  <script src="js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <link href='https://fonts.googleapis.com/css?family=Cabin|Source+Code+Pro' rel='stylesheet' type='text/css'>
</head>
